from pathlib import Path
from typing import TypeVar, Type, Any, Dict, Optional
from dataclasses import dataclass, asdict, fields
import json


T = TypeVar("T", bound="DataModelHelper")


class DataModelHelper:
    """
    Base class for datamodels generated by quicktype.

    This class provides common functionality for datamodels that are automatically
    generated from JSON schemas using quicktype. It establishes a standard interface
    for serialization, deserialization, and file I/O operations.

    Subclasses should implement the from_dict() and to_dict() methods to provide
    type-safe conversion between dictionary representations and dataclass instances.

    Example:
        @dataclass
        class UserModel(DataModelHelper):
            name: str
            age: int

            @staticmethod
            def from_dict(obj: Any) -> "UserModel":
                return UserModel(
                    name=obj["name"],
                    age=obj["age"]
                )

            def to_dict(self) -> dict:
                return {
                    "name": self.name,
                    "age": self.age
                }
    """

    @staticmethod
    def from_dict(obj: Any) -> "DataModelHelper":
        """
        Create an instance from a dictionary representation.

        This method should be overridden in subclasses to provide type-safe
        conversion from dictionary data (typically from JSON) to the specific
        datamodel instance.

        Args:
            obj: Dictionary containing the data to convert. Usually comes from
                 JSON deserialization or API responses.

        Returns:
            An instance of the datamodel subclass.

        Raises:
            NotImplementedError: If not implemented in subclass.
        """
        raise NotImplementedError("from_dict must be implemented by subclasses")

    def to_dict(self) -> dict:
        """
        Convert the instance to a dictionary representation.

        This method should be overridden in subclasses to provide type-safe
        conversion from the datamodel instance to a dictionary suitable for
        JSON serialization or API requests.

        Returns:
            Dictionary representation of the instance.

        Raises:
            NotImplementedError: If not implemented in subclass.
        """
        raise NotImplementedError("to_dict must be implemented by subclasses")

    def save_to_file(self, filename: Path) -> None:
        """
        Save the datamodel instance to a JSON file.

        Converts the instance to a dictionary using to_dict() and saves it
        as formatted JSON with UTF-8 encoding.

        Args:
            filename: Path where the JSON file should be saved.

        Raises:
            OSError: If the file cannot be written.
            NotImplementedError: If to_dict() is not implemented in subclass.
        """
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, ensure_ascii=False, indent=4)

    @classmethod
    def load_from_file(cls: Type[T], filename: Path) -> T:
        """
        Load a datamodel instance from a JSON file.

        Reads JSON data from a file and converts it to an instance using
        the subclass's from_dict() method.

        Args:
            filename: Path to the JSON file to load.

        Returns:
            An instance of the datamodel subclass.

        Raises:
            OSError: If the file cannot be read.
            json.JSONDecodeError: If the file contains invalid JSON.
            NotImplementedError: If from_dict() is not implemented in subclass.
        """
        with open(filename, "r", encoding="utf-8") as f:
            data = json.load(f)
        return cls.from_dict(data)
