#!/bin/bash

set -euo pipefail

# =============================================================================
# Generate UnitSphericalArc Python types from JSON Schema.
# =============================================================================

# === Input schemas (relative to repo root) ===
INPUT_SCHEMA_FILES=(
    "schema/schemas/ModelContextProtocolTypes-schema.json"
    "schema/schemas/MCP/ModelContextProtocol-2025-06-18-schema.json"
)

# === Classes that should inherit from DataModelHelper ===
CLASSES_FOR_BASE_PARENT=(
    "Action"
    "AmbitiousMeta"
    "Argument"
    "Audiocontent"
    "AudiocontentAnnotations"
    "AudiocontentType"
    "Basemetadata"
    "Blobresourcecontents"
    "BooleanschemaClass"
    "BooleanschemaType"
    "BraggadociousMeta"
    "Calltoolrequest"
    "CalltoolrequestMethod"
    "CalltoolrequestParams"
    "Calltoolresult"
    "Cancellednotification"
    "CancellednotificationMethod"
    "CancellednotificationParams"
    "Capabilities"
    "Clientcapabilities"
    "ClientcapabilitiesElicitation"
    "ClientcapabilitiesSampling"
    "ClientcapabilitiesTasks"
    "ClientInfo"
    "Clientnotification"
    "ClientnotificationMethod"
    "ClientnotificationParams"
    "Clientrequest"
    "ClientrequestMethod"
    "ClientrequestParams"
    "Clientresult"
    "CompleterequestClass"
    "CompleterequestMethod"
    "CompleterequestParams"
    "Completeresult"
    "Completion"
    "ContentblockElement"
    "ContentblockType"
    "ContentElement"
    "Context"
    "Createmessagerequest"
    "CreatemessagerequestMethod"
    "CreatemessagerequestParams"
    "CreatemessageresultClass"
    "CunningMeta"
    "Elicitrequest"
    "ElicitrequestMethod"
    "ElicitrequestParams"
    "ElicitresultClass"
    "EmbeddedresourceClass"
    "EmbeddedresourceType"
    "EmptyresultClass"
    "EnumschemaClass"
    "EnumschemaType"
    "Error"
    "Execution"
    "FluffyMeta"
    "FluffyModelContextProtocol20250618_Schema"
    "FluffyRequests"
    "Format"
    "FriskyMeta"
    "GetpromptrequestClass"
    "GetpromptrequestMethod"
    "GetpromptrequestParams"
    "Getpromptresult"
    "HilariousMeta"
    "IconElement"
    "ImagecontentClass"
    "ImagecontentType"
    "IncludeContext"
    "IndecentMeta"
    "IndigoMeta"
    "InitializednotificationClass"
    "InitializednotificationMethod"
    "InitializednotificationParams"
    "InitializerequestClass"
    "InitializerequestMethod"
    "InitializerequestParams"
    "Initializeresult"
    "InputSchema"
    "InputSchemaType"
    "Items"
    "ItemsType"
    "Jsonrpc"
    "Jsonrpcerror"
    "Jsonrpcmessage"
    "JsonrpcnotificationClass"
    "JsonrpcrequestClass"
    "Jsonrpcresponse"
    "Level"
    "ListpromptsrequestClass"
    "ListpromptsrequestMethod"
    "ListpromptsrequestParams"
    "Listpromptsresult"
    "ListresourcesrequestClass"
    "ListresourcesrequestMethod"
    "Listresourcesresult"
    "ListresourcetemplatesrequestClass"
    "ListresourcetemplatesrequestMethod"
    "Listresourcetemplatesresult"
    "Listrootsrequest"
    "ListrootsrequestMethod"
    "ListrootsrequestParams"
    "ListrootsresultClass"
    "ListtoolsrequestClass"
    "ListtoolsrequestMethod"
    "Listtoolsresult"
    "Loggingmessagenotification"
    "LoggingmessagenotificationMethod"
    "LoggingmessagenotificationParams"
    "MagentaMeta"
    "Meta1"
    "MischievousMeta"
    "ModelContextProtocolTypesSchema"
    "ModelhintElement"
    "ModelpreferencesClass"
    "Notification"
    "NumberschemaClass"
    "NumberschemaType"
    "OneOf"
    "OutputSchema"
    "Paginatedrequest"
    "Paginatedresult"
    "ParamsMode"
    "PingrequestClass"
    "PingrequestMethod"
    "PrimitiveschemadefinitionType"
    "PrimitiveschemadefinitionValue"
    "ProgressnotificationClass"
    "ProgressnotificationMethod"
    "ProgressnotificationParams"
    "PromptargumentElement"
    "PromptElement"
    "Promptlistchangednotification"
    "PromptlistchangednotificationMethod"
    "PromptmessageElement"
    "PromptreferenceClass"
    "PromptreferenceType"
    "Prompts"
    "PurpleMeta"
    "PurpleModelContextProtocol20250618_Schema"
    "PurpleRequests"
    "PurpleType"
    "ReadresourcerequestClass"
    "ReadresourcerequestMethod"
    "ReadresourcerequestParams"
    "Readresourceresult"
    "Ref"
    "RefType"
    "Request"
    "RequestedSchema"
    "RequestsElicitation"
    "RequestsSampling"
    "RequestsTools"
    "Resource"
    "Resourcecontents"
    "ResourceElement"
    "ResourcelinkClass"
    "ResourcelinkType"
    "Resourcelistchangednotification"
    "ResourcelistchangednotificationMethod"
    "Resources"
    "ResourcetemplateElement"
    "ResourcetemplatereferenceClass"
    "ResourcetemplatereferenceType"
    "Resourceupdatednotification"
    "ResourceupdatednotificationMethod"
    "ResourceupdatednotificationParams"
    "RoleElement"
    "RootElement"
    "Roots"
    "RootslistchangednotificationClass"
    "RootslistchangednotificationMethod"
    "SamplingmessageElement"
    "ServercapabilitiesTasks"
    "ServercapabilitiesTools"
    "Servernotification"
    "ServernotificationMethod"
    "ServernotificationParams"
    "Serverrequest"
    "ServerrequestMethod"
    "ServerrequestParams"
    "Serverresult"
    "SetlevelrequestClass"
    "SetlevelrequestMethod"
    "SetlevelrequestParams"
    "Status"
    "StickyMeta"
    "StringschemaClass"
    "SubscriberequestClass"
    "SubscriberequestMethod"
    "SubscriberequestParams"
    "Task"
    "TaskElement"
    "TaskSupport"
    "TentacledMeta"
    "TextcontentClass"
    "TextcontentType"
    "TextresourcecontentsClass"
    "Theme"
    "ToolannotationsClass"
    "ToolChoice"
    "ToolChoiceMode"
    "ToolElement"
    "ToollistchangednotificationClass"
    "ToollistchangednotificationMethod"
    "UnsubscriberequestClass"
    "UnsubscriberequestMethod"
    "UnsubscriberequestParams"
    "AnyOf"
)

# === Output (relative to src/foundationTypes) ===
OUTPUT_PYTHON_REL="commonTypes/ModelContextProtocol.py"

# === quicktype target. quicktype only emits up to 3.7; modern typing is
#     restored afterwards by fix_to_dict_return_type + normalization passes. ===
PYTHON_VERSION="3.7"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/reuse/codegen.sh"
source "$SCRIPT_DIR/reuse/add_datamodelhelper.sh"

echo "Generating Python types: $OUTPUT_PYTHON_FILE"
echo "    from schemas: ${INPUT_SCHEMA_FILES[*]}"

setup_quicktype
run_quicktype
add_base_class "$OUTPUT_PYTHON_FILE" "${CLASSES_FOR_BASE_PARENT[@]}"
add_helper_imports "$OUTPUT_PYTHON_FILE"
add_autogen_header "$OUTPUT_PYTHON_FILE"
run_black "$OUTPUT_PYTHON_FILE"
ensure_py_typed "$OUTPUT_PYTHON_FILE"
