#!/bin/bash

set -euo pipefail

# =============================================================================
# Generate UnitSphericalArc Python types from JSON Schema.
# =============================================================================

# === Input schemas (relative to repo root) ===
INPUT_SCHEMA_FILES=(
  "schema/schemas/ModelContextProtocolTypes-schema.json"
  "schema/schemas/MCP/ModelContextProtocol-2025-06-18-schema.json"
)

# === Classes that should inherit from DataModelHelper ===
CLASSES_FOR_BASE_PARENT=(
    
    "Annotations"
    "Argument"
    "AudioContent"
    "BaseMetadata"
    "BlobResourceContents"
    "BooleanSchema"
    "CallToolRequest"
    "CalltoolrequestParams"
    "CallToolResult"
    "CancelledNotification"
    "CancellednotificationParams"
    "ClientCapabilities"
    "ClientNotification"
    "ClientNotificationParams"
    "ClientRequest"
    "ClientRequestParams"
    "ClientResult"
    "ClientResultContent"
    "CompleteRequest"
    "CompleterequestParams"
    "CompleteResult"
    "Completion"
    "ContentBlock"
    "Context"
    "CreateMessageRequest"
    "CreatemessagerequestParams"
    "CreateMessageResult"
    "ElicitRequest"
    "ElicitrequestParams"
    "ElicitResult"
    "EmbeddedResource"
    "EnumSchema"
    "Error"
    "FluffyMeta"
    "GetPromptRequest"
    "GetpromptrequestParams"
    "GetPromptResult"
    "ImageContent"
    "Implementation"
    "IndecentMeta"
    "IndigoMeta"
    "InitializedNotification"
    "InitializednotificationParams"
    "InitializeRequest"
    "InitializerequestParams"
    "InitializeResult"
    "InputSchema"
    "JSONRPCError"
    "JSONRPCMessage"
    "JSONRPCMessageParams"
    "JSONRPCNotification"
    "JsonrpcnotificationParams"
    "JSONRPCRequest"
    "JsonrpcrequestParams"
    "JSONRPCResponse"
    "ListPromptsRequest"
    "ListpromptsrequestParams"
    "ListPromptsResult"
    "ListResourcesRequest"
    "ListresourcesrequestParams"
    "ListResourcesResult"
    "ListResourceTemplatesRequest"
    "ListresourcetemplatesrequestParams"
    "ListResourceTemplatesResult"
    "ListRootsRequest"
    "ListrootsrequestParams"
    "ListRootsResult"
    "ListToolsRequest"
    "ListtoolsrequestParams"
    "ListToolsResult"
    "LoggingMessageNotification"
    "LoggingmessagenotificationParams"
    "ModelContextProtocolTypesSchema"
    "ModelHint"
    "ModelPreferences"
    "Notification"
    "NotificationParams"
    "NumberSchema"
    "OutputSchema"
    "PaginatedRequest"
    "PaginatedrequestParams"
    "PaginatedResult"
    "PingRequest"
    "PingrequestParams"
    "PrimitiveSchemaDefinition"
    "ProgressNotification"
    "ProgressnotificationParams"
    "Prompt"
    "PromptArgument"
    "PromptListChangedNotification"
    "PromptlistchangednotificationParams"
    "PromptMessage"
    "PromptReference"
    "Prompts"
    "PurpleMeta"
    "ReadResourceRequest"
    "ReadresourcerequestParams"
    "ReadResourceResult"
    "Reference"
    "Request"
    "RequestedSchema"
    "RequestParams"
    "Resource"
    "ResourceContents"
    "ResourcecontentsClass"
    "ResourceLink"
    "ResourceListChangedNotification"
    "ResourcelistchangednotificationParams"
    "Resources"
    "ResourceTemplate"
    "ResourceTemplateReference"
    "ResourceUpdatedNotification"
    "ResourceupdatednotificationParams"
    "Result"
    "Root"
    "Roots"
    "RootsListChangedNotification"
    "RootslistchangednotificationParams"
    "SamplingMessage"
    "SamplingmessageContent"
    "ServerCapabilities"
    "ServerNotification"
    "ServerNotificationParams"
    "ServerRequest"
    "ServerRequestParams"
    "ServerResult"
    "SetLevelRequest"
    "SetlevelrequestParams"
    "StickyMeta"
    "StringSchema"
    "SubscribeRequest"
    "SubscriberequestParams"
    "TentacledMeta"
    "TextContent"
    "TextResourceContents"
    "Tool"
    "ToolAnnotations"
    "ToolListChangedNotification"
    "ToollistchangednotificationParams"
    "Tools"
    "UnsubscribeRequest"
    "UnsubscriberequestParams"
)

# === Output (relative to src/foundationTypes) ===
OUTPUT_PYTHON_REL="commonTypes/ModelContextProtocol.py"

# === quicktype target. quicktype only emits up to 3.7; modern typing is
#     restored afterwards by run_ruff (UP rules) + fix_to_dict_return_type. ===
PYTHON_VERSION="3.7"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/reuse/codegen.sh"
source "$SCRIPT_DIR/reuse/add_datamodelhelper.sh"

echo "Generating Python types: $OUTPUT_PYTHON_FILE"
echo "    from schemas: ${INPUT_SCHEMA_FILES[*]}"

setup_quicktype
run_quicktype
add_base_class "$OUTPUT_PYTHON_FILE" "${CLASSES_FOR_BASE_PARENT[@]}"
add_helper_imports "$OUTPUT_PYTHON_FILE"
add_autogen_header "$OUTPUT_PYTHON_FILE"
run_ruff "$OUTPUT_PYTHON_FILE"
ensure_py_typed "$OUTPUT_PYTHON_FILE"
