"""
Base helper class for data model serialization and deserialization.

This module provides the DataModelHelper base class, which standardizes
serialization/deserialization operations for data models generated by quicktype
or manually created. It offers a consistent interface for converting between
Python dataclass instances, dictionaries, and JSON files.
"""

from collections.abc import Callable
from enum import Enum
from json import dump, dumps, load, loads
from logging import getLogger
from os import getenv
from pathlib import Path
from typing import Any, ClassVar, TypeGuard, TypeVar, cast

_log = getLogger(__name__)

DMH = TypeVar("DMH", bound="DataModelHelper")
T = TypeVar("T")
EnumT = TypeVar("EnumT", bound=Enum)


def is_callable(x: object) -> TypeGuard[Callable[..., object]]:
    return callable(x)


def from_bool(x: Any) -> bool:
    if not isinstance(x, bool):
        raise TypeError(f"Expected bool, got {type(x).__name__}")
    return x


def to_class(c: type[DMH], x: Any) -> dict[str, Any]:
    if not isinstance(x, c):
        raise TypeError(f"Expected {c.__name__}, got {type(x).__name__}")
    return x.to_dict()


def from_dict(f: Callable[[Any], T], x: Any) -> dict[str, T]:
    if not isinstance(x, dict):
        raise TypeError(f"Expected dict, got {type(x).__name__}")
    return {k: f(v) for (k, v) in x.items()}


def to_enum(c: type[EnumT], x: Any) -> Any:
    if not isinstance(x, c):
        raise TypeError(f"Expected {c.__name__}, got {type(x).__name__}")
    return x.value


def from_float(x: Any) -> float:
    if not isinstance(x, float | int) or isinstance(x, bool):
        raise TypeError(f"Expected float, got {type(x).__name__}")
    return float(x)


def from_int(x: Any) -> int:
    if not isinstance(x, int) or isinstance(x, bool):
        raise TypeError(f"Expected int, got {type(x).__name__}")
    return x


def to_float(x: Any) -> float:
    return from_float(x)


def from_list(f: Callable[[Any], T], x: Any) -> list[T]:
    if not isinstance(x, list):
        raise TypeError(f"Expected list, got {type(x).__name__}")
    return [f(y) for y in x]


def from_none(x: Any) -> None:
    if x is not None:
        raise TypeError(f"Expected None, got {type(x).__name__}")
    return None


def from_str(x: Any) -> str:
    if not isinstance(x, str):
        raise TypeError(f"Expected str, got {type(x).__name__}")
    return x


def from_union(fs: list[Callable[[Any], Any]], x: Any) -> Any:
    errors: list[str] = []
    for f in fs:
        try:
            return f(x)
        except (TypeError, ValueError, KeyError) as exc:
            errors.append(f"{getattr(f, '__name__', repr(f))}: {exc}")
    summary = repr(x)
    if len(summary) > 200:
        summary = summary[:200] + "..."
    raise ValueError(f"Could not deserialize {summary}; tried: {'; '.join(errors)}")


class DataModelHelper:
    """
    Base class for datamodels generated by quicktype.

    This class provides common functionality for datamodels that are automatically
    generated from JSON schemas using quicktype. It establishes a standard interface
    for serialization, deserialization, and file I/O operations.

    Subclasses should implement the from_dict() and to_dict() methods to provide
    type-safe conversion between dictionary representations and dataclass instances.

    Example:
        @dataclass
        class UserModel(DataModelHelper):
            name: str
            age: int

            @classmethod
            def from_dict(cls, obj: Any) -> "UserModel":
                return cls(
                    name=obj["name"],
                    age=obj["age"]
                )

            def to_dict(self) -> dict:
                return {
                    "name": self.name,
                    "age": self.age
                }
    """

    _env_mapping: ClassVar[dict[str, tuple[str, Any, Callable[[str], Any]]]] = {}
    """
    Mapping of JSON keys to environment variable overrides.

    Format:
        {
            json_key: (env_var_name, default_value, coercion_function)
        }

    Used by from_env() to populate missing configuration values
    from environment variables.
    """

    wire_encode: ClassVar[Callable[..., str] | None] = None
    """
    Optional encoder used for wire-format serialization.

    Must be assigned externally (e.g., wire_config.py).
    """

    wire_decode: ClassVar[Callable[..., Any] | None] = None
    """
    Optional decoder used for wire-format deserialization.

    Must be assigned externally (e.g., wire_config.py).
    """

    @classmethod
    def from_dict(cls: type[DMH], obj: Any) -> DMH:
        """
        Create an instance from a dictionary representation.

        This method should be overridden in subclasses to provide type-safe
        conversion from dictionary data (typically from JSON) to the specific
        datamodel instance.

        Args:
            obj: Dictionary containing the data to convert. Usually comes from
                 JSON deserialization or API responses.

        Returns:
            An instance of the datamodel subclass.

        Raises:
            NotImplementedError: If not implemented in subclass.
        """
        raise NotImplementedError("from_dict must be implemented by subclasses")

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the instance to a dictionary representation.

        This method should be overridden in subclasses to provide type-safe
        conversion from the datamodel instance to a dictionary suitable for
        JSON serialization or API requests.

        Returns:
            Dictionary representation of the instance.

        Raises:
            NotImplementedError: If not implemented in subclass.
        """
        raise NotImplementedError("to_dict must be implemented by subclasses")

    def save_to_file(self, filename: Path) -> None:
        """
        Save the datamodel instance to a JSON file.

        Converts the instance to a dictionary using to_dict() and saves it
        as formatted JSON with UTF-8 encoding.

        Args:
            filename: Path where the JSON file should be saved.

        Raises:
            OSError: If the file cannot be written.
            NotImplementedError: If to_dict() is not implemented in subclass.
        """
        _log.debug("save_to_file: %s -> %s", type(self).__name__, filename)
        try:
            filename.parent.mkdir(parents=True, exist_ok=True)
            with filename.open("w", encoding="utf-8") as f:
                dump(self.to_dict(), f, ensure_ascii=False, indent=4)
            _log.debug("save_to_file: %s saved OK", type(self).__name__)
        except Exception:
            _log.error(
                "save_to_file failed: %s -> %s", type(self).__name__, filename, exc_info=True
            )
            raise

    @classmethod
    def load_from_file(cls: type[DMH], filename: Path) -> DMH:
        """
        Load a datamodel instance from a JSON file.

        Reads JSON data from a file and converts it to an instance using
        the subclass's from_dict() method.

        Args:
            filename: Path to the JSON file to load.

        Returns:
            An instance of the datamodel subclass.

        Raises:
            OSError: If the file cannot be read.
            json.JSONDecodeError: If the file contains invalid JSON.
            NotImplementedError: If from_dict() is not implemented in subclass.
        """
        _log.debug("load_from_file: %s <- %s", cls.__name__, filename)
        try:
            with filename.open(encoding="utf-8") as f:
                data = load(f)
            instance = cls.from_dict(data)
            _log.debug("load_from_file: %s loaded OK", cls.__name__)
            return instance
        except Exception:
            _log.error("load_from_file failed: %s <- %s", cls.__name__, filename, exc_info=True)
            raise

    @classmethod
    def _resolve_from_env(cls, obj: dict[str, Any] | None = None) -> dict[str, Any]:
        """
        Resolve configuration values using environment variables with fallbacks.

        Merges an optional input dictionary with values sourced from environment
        variables defined in `_env_mapping`. For each configured JSON key:

        - If the key is missing or None in `obj`, attempt to read from the
        corresponding environment variable.
        - If the environment variable exists, its value is coerced using the
        provided coercion function.
        - Otherwise, the configured default value is used.

        Args:
            obj: Optional base dictionary of configuration values.

        Returns:
            A new dictionary with all values resolved from input, environment,
            or defaults.

        Notes:
            This method does not perform validation beyond coercion and presence
            checks. It is intended as a preprocessing step before `from_dict()`.
        """
        resolved = dict(obj) if obj else {}
        for json_key, (env_var, default, coercer) in cls._env_mapping.items():
            if json_key not in resolved or resolved[json_key] is None:
                env_val = getenv(env_var)
                if env_val is not None:
                    resolved[json_key] = coercer(env_val)
                else:
                    resolved[json_key] = default
        return resolved

    @classmethod
    def from_env(cls: type[DMH], obj: dict[str, Any] | None = None) -> DMH:
        """
        Create an instance using environment-variable-aware configuration.

        Resolves missing or None values using `_resolve_from_env`, then
        constructs an instance using `from_dict()`.

        Args:
            obj: Optional dictionary overriding environment/default values.

        Returns:
            An initialized datamodel instance.

        Raises:
            NotImplementedError: If `from_dict` is not implemented in subclass.
            Exception: Propagates any errors raised during resolution or construction.

        Notes:
            Useful for configuration-driven models where runtime environment
            variables provide fallback or override behavior.
        """

        _log.debug("from_env: %s", cls.__name__)
        try:
            resolved = cls._resolve_from_env(obj)
            instance = cls.from_dict(resolved)
            _log.debug("from_env: %s loaded OK", cls.__name__)
            return instance
        except Exception:
            _log.error("from_env failed: %s", cls.__name__, exc_info=True)
            raise

    def to_wire(self, **kwargs: Any) -> str:
        """
        Serialize the instance to a wire-format string using a configured encoder.

        Uses the class-level `wire_encode` callable to transform the instance
        into a transport-ready string format (e.g., custom protocol, compact JSON,
        or schema-specific encoding).

        Args:
            **kwargs: Optional keyword arguments forwarded to the encoder.

        Returns:
            A string representing the serialized wire format.

        Raises:
            NotImplementedError: If `wire_encode` is not configured.
            Exception: Propagates errors raised by the encoder.

        Notes:
            The encoder must accept the instance as its first argument.
        """
        encoder = type(self).wire_encode
        if encoder is None:
            raise NotImplementedError(
                f"to_wire not configured for {type(self).__name__}. "
                "Assign wire_encode in wire_config.py."
            )
        _log.debug("to_wire: %s", type(self).__name__)
        try:
            result = encoder(self, **kwargs)  # pylint: disable=not-callable
            # Python has known issue with casting to the callable.  so the check is disabled
            _log.debug("to_wire: %s encoded OK", type(self).__name__)
            return result
        except Exception:
            _log.error("to_wire failed: %s", type(self).__name__, exc_info=True)
            raise

    @classmethod
    def from_wire(cls: "type[DMH]", wire_str: str) -> "DMH":
        """
        Deserialize an instance from a wire-format string using a configured decoder.

        Uses the class-level `wire_decode` callable to reconstruct an instance
        from a transport-format string.

        Args:
            wire_str: Serialized wire-format string.

        Returns:
            A reconstructed instance of the datamodel.

        Raises:
            NotImplementedError: If `wire_decode` is not configured.
            Exception: Propagates errors raised by the decoder.

        Notes:
            The decoder is expected to accept (cls, wire_str) as arguments.
        """

        decoder = cls.wire_decode
        if decoder is None:
            raise NotImplementedError(
                f"from_wire not configured for {cls.__name__}. "
                "Assign wire_decode in wire_config.py."
            )
        _log.debug("from_wire: %s", cls.__name__)
        try:
            instance = cast("DMH", decoder(cls, wire_str))  # pylint: disable=not-callable
            # Python has known issue with casting to the callable.  so the check is disabled
            _log.debug("from_wire: %s decoded OK", cls.__name__)
            return instance
        except Exception:
            _log.error("from_wire failed: %s", cls.__name__, exc_info=True)
            raise

    def to_bytes(self, encoding: str = "utf-8") -> bytes:
        """
        Serialize the instance to UTF-8 encoded JSON bytes.

        Converts the instance to a dictionary via `to_dict()`, serializes it
        to a JSON string, and encodes it into bytes.

        Args:
            encoding: Character encoding used for the output bytes.

        Returns:
            JSON-encoded byte representation of the instance.

        Raises:
            Exception: Propagates errors from serialization or encoding steps.

        Notes:
            This is a convenience method for storage or network transmission
            where raw JSON bytes are required.
        """
        _log.debug("to_bytes: %s", type(self).__name__)
        try:
            result = dumps(self.to_dict(), ensure_ascii=False).encode(encoding)
            _log.debug("to_bytes: %s serialized OK", type(self).__name__)
            return result
        except Exception:
            _log.error("to_bytes failed: %s", type(self).__name__, exc_info=True)
            raise

    @classmethod
    def from_bytes(cls: type[DMH], data: bytes, encoding: str = "utf-8") -> DMH:
        """
        Deserialize an instance from JSON-encoded bytes.

        Decodes bytes into a JSON string, parses it into a dictionary,
        and constructs an instance using `from_dict()`.

        Args:
            data: JSON-encoded byte payload.
            encoding: Character encoding used to decode the input bytes.

        Returns:
            A reconstructed instance of the datamodel.

        Raises:
            Exception: Propagates decoding, JSON parsing, or construction errors.

        Notes:
            This method assumes the input is valid JSON produced by `to_bytes()`
            or a compatible serializer.
        """
        _log.debug("from_bytes: %s (%d bytes)", cls.__name__, len(data))
        try:
            instance = cls.from_dict(loads(data.decode(encoding)))
            _log.debug("from_bytes: %s loaded OK", cls.__name__)
            return instance
        except Exception:
            _log.error("from_bytes failed: %s", cls.__name__, exc_info=True)
            raise
